import datetime
from django.db import models
from djmoney.models.fields import MoneyField
from django.contrib.auth.models import User

TYPE = (
    ('A', 'Air Conditioned'),
    ('NA', 'Non Air Conditioned')
)


def room_images_upload_path(instance, file_name):
    return f"{instance.room_slug}/room_cover/{file_name}"


def room_display_images_upload_path(instance, file_name):
    return f"{instance.room.room_slug}/room_display/{file_name}"


class City(models.Model):
    city_name = models.CharField(max_length=20)

    created_at = models.DateTimeField(default=datetime.datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.datetime.now, blank=True)


class HotelInfo(models.Model):
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    reg_number = models.CharField(max_length=255)
    owner_name = models.CharField(max_length=255, null=True)
    address = models.CharField(max_length=400)
    city = models.ForeignKey('City', on_delete=models.CASCADE, null=True)
    state = models.CharField(max_length=25, null=True)
    phone = models.CharField(max_length=20)
    created_at = models.DateTimeField(default=datetime.datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.datetime.now, blank=True)

    def __str__(self):
        return self.name


class HotelUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    hotel = models.ForeignKey(HotelInfo, on_delete=models.CASCADE)
    is_default = models.BooleanField()


class Room(models.Model):
    title = models.CharField(max_length=30)
    rtype = models.ForeignKey('RoomType', on_delete=models.CASCADE, null=True)
    rfloor = models.IntegerField(default=1, null=True)
    room_slug = "_img"
    cover_image = models.ImageField(upload_to=room_images_upload_path)
    is_active = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    room_status = models.ForeignKey('RoomStatus', on_delete=models.CASCADE, null=True)
    hotel = models.ForeignKey('HotelInfo', on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(default=datetime.datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.datetime.now, blank=True)

    def __str__(self):
        return self.title


class RoomType(models.Model):
    room_type = (('Single room', 'Single room'), ('Twin room', 'Twin room'), ('Double room', 'Double room'),
                 ('Triple room', 'Triple room'), ('Quad room', 'Quad room'),
                 ('Double-Double room', 'Double-Double room'),
                 ('Queen room', 'Queen room'),  ('King room', 'Suite'), ('King room', 'Suite'),
                 ('Presidential suite', 'Presidential suite'), ('Studio', 'Studio'),
                 ('Connecting rooms', 'Connecting rooms'))
    type_name = models.CharField(max_length=20, choices=room_type, default='Twin room')
    area = models.IntegerField(default=10)
    Bed_ = (('1 double bed', '1 double bed'),
            ('1 double bed and 1 Sofa', '1 double bed and 1 Sofa'),
            ('2 single beds', '2 single beds'),
            ('1 Sofa and 1 single bed', '1 Single Sofa Bed and 1 single bed'),
            )
    bedType = models.CharField(max_length=23, choices=Bed_, default='1 double bed')
    capacity = models.IntegerField(default=2)
    price_per_Day = MoneyField(
        decimal_places=2,
        default=0,
        default_currency='USD',
        max_digits=11, )

    description = models.CharField(max_length=30)
    Air_Conditioning = models.BooleanField(default=True)
    wifi = models.BooleanField(default=True)
    tv = models.BooleanField(default=True)
    towels = models.BooleanField(default=True)
    hairdryer = models.BooleanField(default=True)
    bathrobe = models.BooleanField(default=True)
    toiletries = models.BooleanField(default=True)
    heater = models.BooleanField(default=True)
    Shampoo = models.BooleanField(default=True)
    Conditioner = models.BooleanField(default=True)
    bathtub = models.BooleanField(default=True)
    bidet = models.BooleanField(default=True)
    smooking = models.BooleanField(default=True)
    minibar = models.BooleanField(default=True)
    bottled_water = models.BooleanField(default=True)
    coffee = models.BooleanField(default=True)
    Electric_kettle = models.BooleanField(default=True)
    has_window = models.BooleanField(default=True)
    view = models.BooleanField(default=True)

    created_at = models.DateTimeField(default=datetime.datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.datetime.now, blank=True)

    def __str__(self):
        return self.type_name


class RoomStatus(models.Model):
    roomstatus = models.CharField(max_length=30)
    description = models.CharField(max_length=30)
    created_at = models.DateTimeField(default=datetime.datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.datetime.now, blank=True)

    class Meta:
        verbose_name_plural = "Room Status"

    def __str__(self):
        return self.roomstatus


class RoomDisplayImages(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    display_images = models.ImageField(upload_to=room_display_images_upload_path)
    created_at = models.DateTimeField(default=datetime.datetime.now, blank=True)
    updated_at = models.DateTimeField(default=datetime.datetime.now, blank=True)

    def __str__(self):
        return self.room.title


class Availability_Room(models.Model):
    room = models.ForeignKey('Room', on_delete=models.CASCADE)
    d1 = models.IntegerField(default=0)
    d2 = models.IntegerField(default=0)
    d3 = models.IntegerField(default=0)
    d4 = models.IntegerField(default=0)
    d5 = models.IntegerField(default=0)
    d6 = models.IntegerField(default=0)
    d7 = models.IntegerField(default=0)
    d8 = models.IntegerField(default=0)
    d9 = models.IntegerField(default=0)
    d10 = models.IntegerField(default=0)
    d11 = models.IntegerField(default=0)
    d12 = models.IntegerField(default=0)
    d13 = models.IntegerField(default=0)
    d14 = models.IntegerField(default=0)
    d15 = models.IntegerField(default=0)
    d16 = models.IntegerField(default=0)
    d17 = models.IntegerField(default=0)
    d18 = models.IntegerField(default=0)
    d19 = models.IntegerField(default=0)
    d20 = models.IntegerField(default=0)
    d21 = models.IntegerField(default=0)
    d22 = models.IntegerField(default=0)
    d23 = models.IntegerField(default=0)
    d24 = models.IntegerField(default=0)
    d25 = models.IntegerField(default=0)
    d26 = models.IntegerField(default=0)
    d27 = models.IntegerField(default=0)
    d28 = models.IntegerField(default=0)
    d29 = models.IntegerField(default=0)
    d30 = models.IntegerField(default=0)
    d31 = models.IntegerField(default=0)
    d32 = models.IntegerField(default=0)
    d33 = models.IntegerField(default=0)
    d34 = models.IntegerField(default=0)
    d35 = models.IntegerField(default=0)
    d36 = models.IntegerField(default=0)
    d37 = models.IntegerField(default=0)
    d38 = models.IntegerField(default=0)
    d39 = models.IntegerField(default=0)
    d40 = models.IntegerField(default=0)
    d41 = models.IntegerField(default=0)
    d42 = models.IntegerField(default=0)
    d43 = models.IntegerField(default=0)
    d44 = models.IntegerField(default=0)
    d45 = models.IntegerField(default=0)
    d46 = models.IntegerField(default=0)
    d47 = models.IntegerField(default=0)
    d48 = models.IntegerField(default=0)
    d49 = models.IntegerField(default=0)
    d50 = models.IntegerField(default=0)
    d51 = models.IntegerField(default=0)
    d52 = models.IntegerField(default=0)
    d53 = models.IntegerField(default=0)
    d54 = models.IntegerField(default=0)
    d55 = models.IntegerField(default=0)
    d56 = models.IntegerField(default=0)
    d57 = models.IntegerField(default=0)
    d58 = models.IntegerField(default=0)
    d59 = models.IntegerField(default=0)
    d60 = models.IntegerField(default=0)
    d61 = models.IntegerField(default=0)
    d62 = models.IntegerField(default=0)
    d63 = models.IntegerField(default=0)
    d64 = models.IntegerField(default=0)
    d65 = models.IntegerField(default=0)
    d66 = models.IntegerField(default=0)
    d67 = models.IntegerField(default=0)
    d68 = models.IntegerField(default=0)
    d69 = models.IntegerField(default=0)
    d70 = models.IntegerField(default=0)
    d71 = models.IntegerField(default=0)
    d72 = models.IntegerField(default=0)
    d73 = models.IntegerField(default=0)
    d74 = models.IntegerField(default=0)
    d75 = models.IntegerField(default=0)
    d76 = models.IntegerField(default=0)
    d77 = models.IntegerField(default=0)
    d78 = models.IntegerField(default=0)
    d79 = models.IntegerField(default=0)
    d80 = models.IntegerField(default=0)
    d81 = models.IntegerField(default=0)
    d82 = models.IntegerField(default=0)
    d83 = models.IntegerField(default=0)
    d84 = models.IntegerField(default=0)
    d85 = models.IntegerField(default=0)
    d86 = models.IntegerField(default=0)
    d87 = models.IntegerField(default=0)
    d88 = models.IntegerField(default=0)
    d89 = models.IntegerField(default=0)
    d90 = models.IntegerField(default=0)
    d91 = models.IntegerField(default=0)
    d92 = models.IntegerField(default=0)
    d93 = models.IntegerField(default=0)
    d94 = models.IntegerField(default=0)
    d95 = models.IntegerField(default=0)
    d96 = models.IntegerField(default=0)
    d97 = models.IntegerField(default=0)
    d98 = models.IntegerField(default=0)
    d99 = models.IntegerField(default=0)
    d100 = models.IntegerField(default=0)
    d101 = models.IntegerField(default=0)
    d102 = models.IntegerField(default=0)
    d103 = models.IntegerField(default=0)
    d104 = models.IntegerField(default=0)
    d105 = models.IntegerField(default=0)
    d106 = models.IntegerField(default=0)
    d107 = models.IntegerField(default=0)
    d108 = models.IntegerField(default=0)
    d109 = models.IntegerField(default=0)
    d110 = models.IntegerField(default=0)
    d111 = models.IntegerField(default=0)
    d112 = models.IntegerField(default=0)
    d113 = models.IntegerField(default=0)
    d114 = models.IntegerField(default=0)
    d115 = models.IntegerField(default=0)
    d116 = models.IntegerField(default=0)
    d117 = models.IntegerField(default=0)
    d118 = models.IntegerField(default=0)
    d119 = models.IntegerField(default=0)
    d120 = models.IntegerField(default=0)
    d121 = models.IntegerField(default=0)
    d122 = models.IntegerField(default=0)
    d123 = models.IntegerField(default=0)
    d124 = models.IntegerField(default=0)
    d125 = models.IntegerField(default=0)
    d126 = models.IntegerField(default=0)
    d127 = models.IntegerField(default=0)
    d128 = models.IntegerField(default=0)
    d129 = models.IntegerField(default=0)
    d130 = models.IntegerField(default=0)
    d131 = models.IntegerField(default=0)
    d132 = models.IntegerField(default=0)
    d133 = models.IntegerField(default=0)
    d134 = models.IntegerField(default=0)
    d135 = models.IntegerField(default=0)
    d136 = models.IntegerField(default=0)
    d137 = models.IntegerField(default=0)
    d138 = models.IntegerField(default=0)
    d139 = models.IntegerField(default=0)
    d140 = models.IntegerField(default=0)
    d141 = models.IntegerField(default=0)
    d142 = models.IntegerField(default=0)
    d143 = models.IntegerField(default=0)
    d144 = models.IntegerField(default=0)
    d145 = models.IntegerField(default=0)
    d146 = models.IntegerField(default=0)
    d147 = models.IntegerField(default=0)
    d148 = models.IntegerField(default=0)
    d149 = models.IntegerField(default=0)
    d150 = models.IntegerField(default=0)
    d151 = models.IntegerField(default=0)
    d152 = models.IntegerField(default=0)
    d153 = models.IntegerField(default=0)
    d154 = models.IntegerField(default=0)
    d155 = models.IntegerField(default=0)
    d156 = models.IntegerField(default=0)
    d157 = models.IntegerField(default=0)
    d158 = models.IntegerField(default=0)
    d159 = models.IntegerField(default=0)
    d160 = models.IntegerField(default=0)
    d161 = models.IntegerField(default=0)
    d162 = models.IntegerField(default=0)
    d163 = models.IntegerField(default=0)
    d164 = models.IntegerField(default=0)
    d165 = models.IntegerField(default=0)
    d166 = models.IntegerField(default=0)
    d167 = models.IntegerField(default=0)
    d168 = models.IntegerField(default=0)
    d169 = models.IntegerField(default=0)
    d170 = models.IntegerField(default=0)
    d171 = models.IntegerField(default=0)
    d172 = models.IntegerField(default=0)
    d173 = models.IntegerField(default=0)
    d174 = models.IntegerField(default=0)
    d175 = models.IntegerField(default=0)
    d176 = models.IntegerField(default=0)
    d177 = models.IntegerField(default=0)
    d178 = models.IntegerField(default=0)
    d179 = models.IntegerField(default=0)
    d180 = models.IntegerField(default=0)
    d181 = models.IntegerField(default=0)
    d182 = models.IntegerField(default=0)
    d183 = models.IntegerField(default=0)
    d184 = models.IntegerField(default=0)
    d185 = models.IntegerField(default=0)
    d186 = models.IntegerField(default=0)
    d187 = models.IntegerField(default=0)
    d188 = models.IntegerField(default=0)
    d189 = models.IntegerField(default=0)
    d190 = models.IntegerField(default=0)
    d191 = models.IntegerField(default=0)
    d192 = models.IntegerField(default=0)
    d193 = models.IntegerField(default=0)
    d194 = models.IntegerField(default=0)
    d195 = models.IntegerField(default=0)
    d196 = models.IntegerField(default=0)
    d197 = models.IntegerField(default=0)
    d198 = models.IntegerField(default=0)
    d199 = models.IntegerField(default=0)
    d200 = models.IntegerField(default=0)
    d201 = models.IntegerField(default=0)
    d202 = models.IntegerField(default=0)
    d203 = models.IntegerField(default=0)
    d204 = models.IntegerField(default=0)
    d205 = models.IntegerField(default=0)
    d206 = models.IntegerField(default=0)
    d207 = models.IntegerField(default=0)
    d208 = models.IntegerField(default=0)
    d209 = models.IntegerField(default=0)
    d210 = models.IntegerField(default=0)
    d211 = models.IntegerField(default=0)
    d212 = models.IntegerField(default=0)
    d213 = models.IntegerField(default=0)
    d214 = models.IntegerField(default=0)
    d215 = models.IntegerField(default=0)
    d216 = models.IntegerField(default=0)
    d217 = models.IntegerField(default=0)
    d218 = models.IntegerField(default=0)
    d219 = models.IntegerField(default=0)
    d220 = models.IntegerField(default=0)
    d221 = models.IntegerField(default=0)
    d222 = models.IntegerField(default=0)
    d223 = models.IntegerField(default=0)
    d224 = models.IntegerField(default=0)
    d225 = models.IntegerField(default=0)
    d226 = models.IntegerField(default=0)
    d227 = models.IntegerField(default=0)
    d228 = models.IntegerField(default=0)
    d229 = models.IntegerField(default=0)
    d230 = models.IntegerField(default=0)
    d231 = models.IntegerField(default=0)
    d232 = models.IntegerField(default=0)
    d233 = models.IntegerField(default=0)
    d234 = models.IntegerField(default=0)
    d235 = models.IntegerField(default=0)
    d236 = models.IntegerField(default=0)
    d237 = models.IntegerField(default=0)
    d238 = models.IntegerField(default=0)
    d239 = models.IntegerField(default=0)
    d240 = models.IntegerField(default=0)
    d241 = models.IntegerField(default=0)
    d242 = models.IntegerField(default=0)
    d243 = models.IntegerField(default=0)
    d244 = models.IntegerField(default=0)
    d245 = models.IntegerField(default=0)
    d246 = models.IntegerField(default=0)
    d247 = models.IntegerField(default=0)
    d248 = models.IntegerField(default=0)
    d249 = models.IntegerField(default=0)
    d250 = models.IntegerField(default=0)
    d251 = models.IntegerField(default=0)
    d252 = models.IntegerField(default=0)
    d253 = models.IntegerField(default=0)
    d254 = models.IntegerField(default=0)
    d255 = models.IntegerField(default=0)
    d256 = models.IntegerField(default=0)
    d257 = models.IntegerField(default=0)
    d258 = models.IntegerField(default=0)
    d259 = models.IntegerField(default=0)
    d260 = models.IntegerField(default=0)
    d261 = models.IntegerField(default=0)
    d262 = models.IntegerField(default=0)
    d263 = models.IntegerField(default=0)
    d264 = models.IntegerField(default=0)
    d265 = models.IntegerField(default=0)
    d266 = models.IntegerField(default=0)
    d267 = models.IntegerField(default=0)
    d268 = models.IntegerField(default=0)
    d269 = models.IntegerField(default=0)
    d270 = models.IntegerField(default=0)
    d271 = models.IntegerField(default=0)
    d272 = models.IntegerField(default=0)
    d273 = models.IntegerField(default=0)
    d274 = models.IntegerField(default=0)
    d275 = models.IntegerField(default=0)
    d276 = models.IntegerField(default=0)
    d277 = models.IntegerField(default=0)
    d278 = models.IntegerField(default=0)
    d279 = models.IntegerField(default=0)
    d280 = models.IntegerField(default=0)
    d281 = models.IntegerField(default=0)
    d282 = models.IntegerField(default=0)
    d283 = models.IntegerField(default=0)
    d284 = models.IntegerField(default=0)
    d285 = models.IntegerField(default=0)
    d286 = models.IntegerField(default=0)
    d287 = models.IntegerField(default=0)
    d288 = models.IntegerField(default=0)
    d289 = models.IntegerField(default=0)
    d290 = models.IntegerField(default=0)
    d291 = models.IntegerField(default=0)
    d292 = models.IntegerField(default=0)
    d293 = models.IntegerField(default=0)
    d294 = models.IntegerField(default=0)
    d295 = models.IntegerField(default=0)
    d296 = models.IntegerField(default=0)
    d297 = models.IntegerField(default=0)
    d298 = models.IntegerField(default=0)
    d299 = models.IntegerField(default=0)
    d300 = models.IntegerField(default=0)
    d301 = models.IntegerField(default=0)
    d302 = models.IntegerField(default=0)
    d303 = models.IntegerField(default=0)
    d304 = models.IntegerField(default=0)
    d305 = models.IntegerField(default=0)
    d306 = models.IntegerField(default=0)
    d307 = models.IntegerField(default=0)
    d308 = models.IntegerField(default=0)
    d309 = models.IntegerField(default=0)
    d310 = models.IntegerField(default=0)
    d311 = models.IntegerField(default=0)
    d312 = models.IntegerField(default=0)
    d313 = models.IntegerField(default=0)
    d314 = models.IntegerField(default=0)
    d315 = models.IntegerField(default=0)
    d316 = models.IntegerField(default=0)
    d317 = models.IntegerField(default=0)
    d318 = models.IntegerField(default=0)
    d319 = models.IntegerField(default=0)
    d320 = models.IntegerField(default=0)
    d321 = models.IntegerField(default=0)
    d322 = models.IntegerField(default=0)
    d323 = models.IntegerField(default=0)
    d324 = models.IntegerField(default=0)
    d325 = models.IntegerField(default=0)
    d326 = models.IntegerField(default=0)
    d327 = models.IntegerField(default=0)
    d328 = models.IntegerField(default=0)
    d329 = models.IntegerField(default=0)
    d330 = models.IntegerField(default=0)
    d331 = models.IntegerField(default=0)
    d332 = models.IntegerField(default=0)
    d333 = models.IntegerField(default=0)
    d334 = models.IntegerField(default=0)
    d335 = models.IntegerField(default=0)
    d336 = models.IntegerField(default=0)
    d337 = models.IntegerField(default=0)
    d338 = models.IntegerField(default=0)
    d339 = models.IntegerField(default=0)
    d340 = models.IntegerField(default=0)
    d341 = models.IntegerField(default=0)
    d342 = models.IntegerField(default=0)
    d343 = models.IntegerField(default=0)
    d344 = models.IntegerField(default=0)
    d345 = models.IntegerField(default=0)
    d346 = models.IntegerField(default=0)
    d347 = models.IntegerField(default=0)
    d348 = models.IntegerField(default=0)
    d349 = models.IntegerField(default=0)
    d350 = models.IntegerField(default=0)
    d351 = models.IntegerField(default=0)
    d352 = models.IntegerField(default=0)
    d353 = models.IntegerField(default=0)
    d354 = models.IntegerField(default=0)
    d355 = models.IntegerField(default=0)
    d356 = models.IntegerField(default=0)
    d357 = models.IntegerField(default=0)
    d358 = models.IntegerField(default=0)
    d359 = models.IntegerField(default=0)
    d360 = models.IntegerField(default=0)
    d361 = models.IntegerField(default=0)
    d362 = models.IntegerField(default=0)
    d363 = models.IntegerField(default=0)
    d364 = models.IntegerField(default=0)
    d365 = models.IntegerField(default=0)
    d366 = models.IntegerField(default=0)
